module.exports = {

    feed: 'Feed',
    stream: 'Stream',
    streams: 'Streams',
    list: 'List',
    lists: 'Lists',
    favourite: 'Favourite',
    favourites: 'Favourites',
    to_favourites: 'to favourites',
    in_your_favourites: 'In your favourites',

    author: 'Journalist',
    authors: 'Journalists',
    all_authors: 'All Journalists',
    view_authors: 'View journalists',
    count_authors: '%{count} journalists',

    about: 'About',
    all: 'All',
    headlines: 'Headlines',

    outlet: 'Outlet',
    outlets: 'Outlets',
    view_outlets: 'View outlets',
    count_outlets: '%{count} outlets',

    desk: 'Desk',
    desks: 'Desks',
    bureaus: 'Bureaus',
    company: 'Company',
    companies: 'Companies',
    person: 'Person',
    topic: 'Topic',
    topics: 'Topics',
    article: 'Article',
    articles: 'Articles',
    personal: 'Personal',
    premade: 'Pre-made',
    settings: 'Settings',
    activity: 'Activity',
    activities: 'Activities',
    creating: 'Creating...',
    log: 'Change log',
    search: 'Search',
    browse: 'Browse',
    name: 'Name',
    shared: 'Shared',
    sector: 'Sector',
    sectors: 'Sectors',
    outlet_type: 'Outlet type',
    outlet_filter_placeholder: 'Enter outlet name...',
    author_filter_placeholder: 'Enter journalist name...',
    contact: 'Contact',
    contact_details: 'Contact details',
    type: 'Type',
    circulation: 'Circulation',
    circulation_for: 'Circulation for',
    frequency: 'Frequency',
    results: 'Results',
    emails: 'Emails',
    email: 'Email',
    login_email_placeholder: 'Enter your email...',
    password: 'Password',
    login_password_placeholder: 'Enter your password...',
    phone: 'Phone',
    mobile: 'Mobile',
    website: 'Website',
    facebook: 'Facebook',
    linkedin: 'LinkedIn',
    address: 'Address',
    addresses: 'Addresses',
    circulation_print: 'Print circulation',
    circulation_online: 'Online circulation',
    deadline_week_day: 'Deadline week day',
    deadline_date: 'Deadline date',
    details: 'Details',
    presences: 'Presences',
    work: 'Work',
    coverage: 'Coverage',
    coverage_on: 'Coverage on',
    before: 'Before...',
    deleting: 'Deleting...',
    no_items: 'No items to display.',
    ungroup: 'Un-group',
    edit: 'Edit',
    delete: 'Delete',
    description: 'Description',
    enter_list_description: 'Enter a description for this list...',
    email_address_support: 'help@roxhillmedia.com',
    go_to_top: 'Go to top',
    show_all: 'Show all',
    timeframe: 'Timeframe',
    timeframe_after_placeholder: 'On or since...',
    based_in: 'Based in',
    pick_countries: 'Pick countries...',
    circulating_in: 'Circulating in or around...',
    anywhere: 'Anywhere',
    ordered_by: 'ordered by',
    coverage_by_authors_since: 'Coverage by journalists in national papers in the last',
    vcard: 'vCard',
    for: 'for',
    outlets_all: 'all outlets',
    in_the_last: 'in the last',
    search_timeframe_tip: 'Defaults to the last 6 months.',
    overview: 'Overview',

    feedback_author_position: 'This journalist has changed position.',
    feedback_author_contact: 'This journalist\'s contact information has changed.',
    feedback_outlet_contact: 'This outlet\'s contact information has changed.',
    feedback_company_contact: 'This company\'s contact information has changed.',
    feedback_help: 'I would like help using the site.',
    feedback_suggestion: 'I have a suggestion for improving this page.',
    feedback_details_title: 'Please include details below:',

    stream_selector_placeholder: 'Select streams here or type in the name of a new stream to create',
    list_selector_placeholder: 'Select lists here or type in the name of a new list to create',
    stream_selector_placeholder_short: 'Pick streams to add to',
    list_selector_placeholder_short: 'Pick lists to add to',

    author_headlines_only_national: 'Headlines will only appear for UK national newspaper journalists.',

    login_issue_tip: 'If you have any issues accessing your account, or while using the application, please contact us at',

    application_brand: 'Roxhill Media',

    log_in_loading_text: 'Logging in...',
    log_in: 'Log in',

    update: 'Update',
    updating: 'Updating...',
    rename: 'Rename',
    short_note: 'Roxhill says',
    twitter: 'Twitter',
    categories: 'Categories',
    record_activity: 'Record activity',
    edit_activity: 'Edit an activity',
    delete_activity: 'Delete an activity',
    press_officer: 'Press officer',
    spokesperson: 'Spokesperson',
    issue: 'Issue',
    status: 'Status',
    action: 'Action',
    client: 'Client',
    campaign: 'Campaign',
    date: 'Date',
    time: 'Time',
    keyword: 'Keyword',
    biography: 'Biography',
    tweets: 'Tweets',
    tweets_list_loading: 'Loading tweets...',
    tweets_list_empty: 'No tweets',
    followers: 'Followers',
    following: 'Following',
    retweet: 'Retweet',
    retweets: 'Retweets',
    attachment: 'Attachment',
    add_journos: 'Search journalists to add...',
    add_outlets: 'Search outlets to add...',
    team: 'Team',
    notes: 'Notes',
    notes_placeholder: 'Notes...',
    my_streams: 'My streams',
    subject: 'Subject',
    download: 'Download',
    download_document: 'Download document',
    error: 'Error!',
    company_sectors: 'Company Sectors',
    create_new_item_dropdown: 'Click here to create new %{type} called <strong>%{name}</strong>&hellip;',
    briefing_document: 'Briefing document',
    go: 'Go',
    filter: 'Filter',
    filters: 'Filters',
    clear_filters: 'Clear filters',
    select_all: 'Select all',
    clear_selection: 'Clear selection',
    organise: 'Organise',
    add_to: 'Add to...',
    pivot: 'Pivot',
    export: 'Export',
    fifty_emails_tip: 'For more than 50 email addresses, please use the \'Copy\' button to the left.',
    group: 'Group',
    saving: 'Saving...',
    save_changes: 'Save changes',
    enter_list_name: 'Enter a name for this list...',
    add: 'Add',
    remove: 'Remove',
    rankings: 'Rankings',
    set_date: 'Set date...',
    set_time: 'Set time...',
    quick_search_placeholder: 'Find it quickly',
    sources: 'Sources',
    in: 'In',
    and: 'and',
    add_to_streams_and_lists: 'Add to streams &amp; lists',
    show_more: 'Show more',
    summary: 'Summary',

    author_delete: 'Delete author',
    assigned_to: 'assigned to',
    unassigned_from: 'unassigned from',
    moved_to: 'moved to',
    at: 'at',

    author_deleted: 'Deleted journalist',
    added: 'Added',
    removed: 'Removed',
    user_deleted: 'Deleted user',
    not_available: 'n/a',

    dropzone_tip: 'Click or drag file here to upload attachment',

    browse_sectors: 'Browse sectors',
    browse_topics: 'Browse topics',
    browse_activities: 'Browse activities',

    author_alerts: 'Journalist alerts',

    mon: 'Mon',
    tue: 'Tues',
    wed: 'Weds',
    thu: 'Thurs',
    fri: 'Fri',
    sat: 'Sat',
    sun: 'Sun',

    move_count_to: 'Move %{count} to...',
    copy_count_to: 'Copy %{count} to...',
    delete_count: 'Delete %{count}',
    add_count_to_streams: 'Add %{count} to streams',
    add_count_to_lists: 'Add %{count} to lists',
    download_count_to_excel: 'Download %{count} to Excel',
    print_count_labels: 'Print %{count} labels',
    copy_count_emails: 'Copy %{count} emails',
    search_count_outlet_authors: 'Search %{count} outlet\'s journalists',

    favourites_tip_header: 'Using your favourites',
    favourites_tip_one: 'You can add any journalist, outlet or desk to your favourites and they will appear here.',
    favourites_tip_two: 'To add a favourite, simply go to a journalist, outlet or desk page and click the \'Add to favourites\' button at the top right corner of their profile.',
    go_to_search: 'Go to search',

    favourites_feed_tip_header: 'Your favourites feed',
    favourites_feed_tip_one: 'This feed will display articles written by any of your favourite journalists. In order to populate this feed please choose the journalists you would like to follow by adding them to your favourites.',

    authors_selector_placeholder: 'Choose journalists...',

    notification_filter_tip: 'What type of notifications would you like to see?',
    sources_selector_tip: 'Where would you like to see notifications from?',

    toolbar_search: 'Search',
    toolbar_user_account_manager: 'Account managers',
    toolbar_user_logout: 'Log out',
    toolbar_report_inaccuracy: 'Feedback',
    toolbar_help: 'Help',
    toolbar_help_blurb: 'Need help using Roxhill?',

    stream_item_remove_confirm: 'Are you sure you want to remove item from the stream?',
    stream_edit: 'Edit stream',

    list_filter_no_authors: 'There are no journalists in this list with that name.',
    list_empty: 'This list is empty.',
    list_empty_tip: 'Use the search tab at the top of the page to find what you are looking for and populate your list.',

    list_item_remove_confirm: 'Are you sure you want to remove %{item} from %{feed}?',
    list_item_remove_ok: '%{item} was removed from %{feed}!',
    list_item_remove_err: 'Removing %{item} from %{feed} failed! Please try again.',

    list_move_title: 'Select lists to move journalists to',
    list_move_btn_ok: 'Move journalists',
    list_move_btn_cancel: 'Cancel',
    list_move_msg_ok: 'Journalists moved successfully!',
    list_move_msg_err: 'Moving journalists failed. Please try again!',

    list_copy_title: 'Select lists to copy journalists to',
    list_copy_btn_ok: 'Copy journalists',
    list_copy_btn_cancel: 'Cancel',
    list_copy_msg_ok: 'Journalists copied successfully!',
    list_copy_msg_err: 'Copying journalists failed. Please try again!',

    list_remove_title: 'Are you sure you want to remove the %{count} selected authors?',
    list_remove_msg_ok: 'The selected journalists were removed from %{feed}.',
    list_remove_msg_err: 'Removing journalists from %{feed} failed. Please try again!',


    lists_none_header: 'Welcome to your lists',
    lists_none_info: 'Roxhill helps you to easily manage your contacts with folders and lists. Once you have created a list, use the Search tab at the top of the page to populate it.',
    get_started: 'Get started',
    lists_none_tip: 'To get started, let\'s create a folder with a list inside it:',
    folder_name: 'Folder name',
    folder_name_placeholder:'Enter a folder name...',
    list_name: 'List name',
    list_name_placeholder: 'Enter a list name...',
    loading: 'Loading...',

    list_delete: 'Delete list',

    streams_none_header: 'Using your streams',
    streams_none_info: 'Roxhill Streams will help you to keep track of the news that matters to you. By creating a bespoke stream, you can follow journalists, companies and topics.',
    streams_none_tip: 'To get started, let\'s create a stream:',
    stream_name: 'Stream name',
    stream_name_placeholder: 'Enter a stream name...',


    stream_emails_title: 'Email notification settings',
    stream_emails_dont_email: 'Don\'t email me.',
    stream_emails_email_everytime: 'Email me every time a notification appears in the stream.',
    stream_emails_email_summary: 'Email me a summary of the activity in this stream:',
    stream_emails_email_at_times: 'Email me a summary of the activity in this stream at specific times:',
    stream_emails_every_morning: 'Every morning (7am)',
    stream_emails_every_lunchtime: 'Every lunchtime (12pm)',
    stream_emails_every_evening: 'Every evening (5pm)',
    stream_emails_even_on_weekends: 'Even on weekends',
    stream_emails_choose_time: 'Time…',
    stream_emails_time_format_alert: 'Time must be in the formated like 7:00, 10:00 etc',
    notification_types: 'Notification types',

    favourite_item_add_ok: '%{item} was added to your favourites!',
    favourite_item_add_err:  'Updating your favourties failed, please try again!',
    favourite_item_remove_ok: '%{item} was removed from your favourites!',
    favourite_item_remove_err: 'Updating your favourties failed, please try again!',

    feed_item_updated_ok: 'Your feeds were updated with %{item}!',
    feed_item_updated_err: 'Updating your feeds with %{item} failed, please try again!',
    feed_item_removed_msg: 'Are you sure you want to remove %{item}?',
    feed_item_removed_ok: '%{item} was removed!',
    feed_item_removed_err: 'Removing %{item} failed. Please try again!',

    search_no_results: 'There are no matching results to display!',

    search_empty_header: 'Using search',
    search_empty_tip_one: 'Use the green tabs to switch between searching journalists, outlets, articles, tweets and your activities.',
    search_empty_tip_two: 'Use the filters on the left to refine and execute your search.',
    search_empty_tip_three: 'Use the blue toolbar to export, email, or add your results to lists and streams.',

    stream_empty_header: 'This stream is empty.',
    stream_empty_tip: 'Add items to your stream page to follow journalists, companies, outlets, sectors and topics that matter to you.',


    home_feeds_favourites: 'Favourites',
    alerts: 'Alerts',

    streams_create: 'Create new stream',
    streams_delete: 'Delete',
    streams_in: '%{smart_count} stream |||| %{smart_count} streams',
    streams_show_on_homepage: 'Show on homepage',
    streams_remove_from_homepage: 'Remove from homepage',

    list_create: 'Create list',
    folder_create: 'Create folder',
    list_add: 'Add to this list',
    list_move_confirm_msg: 'Are you sure you want to move <em>%{child}</em> into <em>%{parent}</em>?',
    list_move_confirm_msg_root: 'Are you sure you want to move <em>%{child}</em>?',
    lists_in: '%{smart_count} list |||| %{smart_count} lists',

    search_filters: 'Filters',
    search_filters_required: 'Please specify some filters before searching!',

    search_button: 'Search',
    search_button_loading: 'Searching...',
    search_outlet: 'Outlet',
    search_outlets: 'Outlets',
    search_outlet_placeholder: 'Choose outlets...',
    search_outlet_type: 'Outlet type',
    search_outlet_types: 'Outlet types',
    search_outlet_type_placeholder: 'Choose outlet type...',
    search_outlet_tag: 'Sector',
    search_outlet_tags: 'Sectors',
    search_outlet_tag_placeholder: 'Choose sector...',
    search_author_sector: 'Sector',
    search_author_sector_placeholder: 'Choose sectors...',
    search_activity_tag: 'Activity',
    search_activity_tag_spokesperson: 'Spokesperson',
    search_activity_tags: 'Activity tags',
    search_activity_tag_placeholder: 'Choose activity tags...',
    search_activity_tag_spokesperson_placeholder: 'Choose spokespersons...',
    search_activity_pr: 'Press office',
    search_activity_pr_pro_placeholder: 'Choose press officers...',
    search_topic: 'Topic',
    search_topics: 'Topics',
    search_topic_placeholder: 'Choose topics...',
    search_keyword: 'Keyword',
    search_keyword_placeholder: 'Choose keywords...',
    search_companies: 'Companies',
    search_company_placeholder: 'Choose companies...',
    search_company_sector_placeholder: 'Choose company sectors...',

    search_browse_author_tags_title: 'Choose sectors',
    search_browse_author_tags_btn_ok: 'Choose selected sectors',
    search_browse_author_tags_btn_cancel: 'Cancel',


    search_browse_article_tags_title: 'Choose topics',
    search_browse_article_tags_btn_ok: 'Choose selected topics',
    search_browse_article_tags_btn_cancel: 'Cancel',

    search_browse_company_tags_title: 'Choose company sectors',
    search_browse_company_tags_btn_ok: 'Choose selected sectors',
    search_browse_company_tags_btn_cancel: 'Cancel',

    search_browse_activity_tags_title: 'Choose activity tags',
    search_browse_activity_tags_btn_ok: 'Choose selected tags',
    search_browse_activity_tags_btn_cancel: 'Cancel',

    pick: 'Pick',
    hide: 'Hide',

    search_coverage_by_address: 'By any town or postcode',
    search_coverage_by_custom_area: 'By custom area',
    search_coverage_by_map_area: 'By visible map area',
    search_coverage_by_custom_area_draw: 'Draw area',
    search_coverage_by_custom_area_draw_loading: 'Click the map',
    search_coverage_by_custom_area_clear: 'Clear area',
    search_coverage_by_map_area_instructions: 'Pan and zoom the map to define the area you wish to search in.',

    display_grid: 'Display as grid',
    display_table: 'Display as table',
    display_chart: 'Display as chart',
    display_map: 'Display on map',

    article_tile_l1_toggle_show: 'Show details',
    article_tile_l1_toggle_hide: 'Hide details',
    article_tile_l2_companies: 'Companies',
    article_tile_l2_company_tags: 'Sectors',
    article_tile_l2_story_tags: 'Topics',
    article_tile_l2_metadata: 'Section',
    article_tile_l2_none: 'None',
    article_tile_l2_excerpt: 'Excerpt',

    author_list_log_time: 'Time',
    author_list_log_author: 'Journalist',
    author_list_log_action: 'Action',
    author_list_log_user: 'User',
    author_list_log_movement: 'Movement',
    author_list_log_desk: 'Desk',
    author_list_log_outlet: 'Outlet',
    author_list_log_job_title: 'Job title',

    author_coverage_only_national: 'Coverage will only appear for UK national newspaper journalists.',


    show_all_warning: 'You are choosing to display over %{smart_count} items. This may adversely affect the performance of your browser, so we will only display up to 500 items at once. Show all items?',
    article_count: '%{smart_count} hit |||| %{smart_count} hits',
    processing_data: 'Processing data...',
    data_unavailable: 'No data is available.',

    report_inaccuracy_placeholder: 'Enter your message here...',
    report_inaccuracy_title: 'Your feedback',
    report_inaccuracy_btn_ok: 'Send feedback',
    report_inaccuracy_btn_cancel: 'Cancel',
    report_inaccuracy_msg_ok: 'Thank you for your feedback!',
    report_inaccuracy_msg_err: 'Sending feedback has failed. Please try again!',

    activity_delete_title: 'Are you sure you wish to delete this activity?',
    activity_delete_msg_ok: 'Activity deleted!',
    activity_delete_msg_err: 'Activity deletion failed, please try again.'
};
